services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=postgres;Database=rpslsDb;Username=postgres;Password=postgres
    depends_on:
      - postgres
    command: >
      sh -c "sleep 10 && 
             dotnet ef database update --project src/rpsls.Infrastructure --startup-project src/rpsls.Api --no-build && 
             dotnet rpsls.Api.dll"
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rpslsDb
    ports:
      - "5432:5432"